### ISSUE TITLE
Apply-PnPProvisioningTemplate : Column 'ClientSideApplicationId' does not exist

### ISSUE THREAD

**Issue by timguyuk** [EduRemoteLearning/365edulearning#1]
Hi

Running Apply-PnPProvisioningTemplate -Path .\RemoteLearningTemplate.xml Im getting:

Apply-PnPProvisioningTemplate : Column 'ClientSideApplicationId' does not exist. It may have been deleted by another user.  /SitePages

Las part of the debug:
powershell.exe Information: 0 : 2020-04-29 12:58:55.9926        [Site Security] [10]    [Debug] Code execution scope ended      3100ms  16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:55.9926        [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope started    0ms     16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:55.9926        [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope ended      0ms     16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:56.0082        [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope started    0ms     16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:56.0082        [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope ended      0ms     16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:56.0082        [ClientSidePages]       [10]    [Debug] Code execution scope started    0ms     16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:56.8776        [ClientSidePages]       [10]    [Debug] Code execution scope ended      857ms   16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:56.8788        [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope started    0ms     16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:56.8795        [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope ended      0ms     16052706-8f73-446d-80d5-ca149dd778cf
powershell.exe Information: 0 : 2020-04-29 12:58:56.8795        [Provisioning]  [10]    [Debug] Code execution scope ended      5422ms  16052706-8f73-446d-80d5-ca149dd778cf

I can see  that its created IT.aspx, School-leaders.aspx, Educators.asp and stopped.

tenant was old and dorment but default sharepoint site is fresh, no changes that Im aware of.

Tim

**Comment by timguyuk** [comment]
Sorted, Re-copied images into asset and its pushed me further.

**Comment by timguyuk** [comment]
Maybe not, so I'm now stucked between:

Apply-PnPProvisioningTemplate : Page Home.aspx is not a "modern" client side page

The suggestion is to delete the page and let the template recreate it, it does recreate the page but then ends with:

Apply-PnPProvisioningTemplate : Column 'ClientSideApplicationId' does not exist. It may have been deleted by another user. /SitePages

and If Ire-run I get:

Apply-PnPProvisioningTemplate : Page Home.aspx is not a "modern" client side page again

Tim

**Comment by EduRemoteLearning** [comment]
Did you create the new site collection as #STS3 template?

**Comment by timguyuk** [comment]
I didn't, I was trying to modify the default site home.aspx. This tenant was 2013 created, Ive read that you need to create a new modern site and replace the old site which Im in the process of doing, Ive got the new site created but getting the errors / wait 10 mins so I guess theres background creation still running.

**Comment by EduRemoteLearning** [comment]
let me know how you get on

**Comment by timguyuk** [comment]
Ok so the suggestion is to create a new modern site and then replace the default site with this newly created one.

The new site has to be a non-365 group site and so in the current portal you create it as a 'other option' team site.

Using the portal 'replace site' didn't work for me, I had to use powershell. Also on this tenant I had to follow this and make sure the publishing features where enabled (tip when you click activate it takes a while, don't click off the page)

https://support.microsoft.com/en-gb/office/enable-publishing-features-479677a6-8b33-4ac7-907d-071c1c7e4518?ui=en-us&rs=en-gb&ad=gb

Then this command worked:

Invoke-SPOSiteSwap -SourceUrl https://theschool.sharepoint.com/sites/theschoolSchoolLearning -TargetUrl https://theschool.sharepoint.com -ArchiveUrl https://https://theschool.sharepoint.com/sites/Archive -force

Defo need the -force

Thanks
