### ISSUE TITLE
NewSiteCollection.ps1 - Not Working!

### ISSUE THREAD

**Issue by anaylor130683** [EduRemoteLearning/365edulearning#2]
Good Afternoon

I have tried to use the "Landing Page" powershell script and the last command keeps failing.

When the script runs
Apply-PnPProvisioningTemplate -Path ($path + "RemoteLearningTemplate.xml") 

It starts to apply the template to the new site created, however then it errors:
![capture1](https://user-images.githubusercontent.com/43571211/80983754-d6af4900-8e24-11ea-8ace-1efe5eb3ccfc.JPG)
![capture2](https://user-images.githubusercontent.com/43571211/80983759-d9aa3980-8e24-11ea-9bee-7798a8f51de8.JPG)

**Comment by EduRemoteLearning** [comment]
hi - can you confirm that you've used the STS3 template?  The home page should be the new modern sharepoint page.  If not, delete the home page and create a new one as home.aspx ensure it is a new modern sharepoint page.  Let me know how you get on.

**Comment by anaylor130683** [comment]
Hi the command in the script is:

New-SPOSite -Url $URL -Owner $siteCollectionAdmin -Title "Remote Learning" -Template STS#3 -StorageQuota 1000

So assuming when it created the site it is using the **STS3** template that you mention.
I am using the "NewSiteCreation.ps1"

So the sharepoint site is created "Remote Learning"
The images are uploaded and appear in the "Site Assets" in the new site

When the "Apply-PnPProvisioningTemplate command it starts to apply the template as you can see from my previous screen shots, then the error appears.

Below screen shot shows what you are left with
![remotelearning](https://user-images.githubusercontent.com/43571211/81005084-4a614e00-8e45-11ea-86ff-814254639e29.JPG)

**Comment by EduRemoteLearning** [comment]
Can you let me know you powershell version please.
Get-Module SharePointPnPPowerShellOnline* -ListAvailable | select name,version

Thanks

Alex

**Comment by anaylor130683** [comment]
Good Morning Alex

Please see below

![psversion](https://user-images.githubusercontent.com/43571211/81042617-6ea24680-8ea8-11ea-8e53-1200f7a4c152.JPG)

**Comment by anaylor130683** [comment]
Hi Alex

Start from scratch for another customer this afternoon and edited the "NewSiteCollection.ps1" powershell as required again.

Script completed through until the end again, when it starts to apply template but then the same below error appears again

Are you any closer to an answer or have another way to apply the XML template to the site?

![fails](https://user-images.githubusercontent.com/43571211/81069337-a5dd1b80-8ed9-11ea-802a-ace196d56e5b.JPG)

**Comment by anaylor130683** [comment]
Microsoft support (Office 365) came back to me although they said they do not support scripting.
The only thing they could recommend is:

Use the Set-SPOsite -DenyAddAndCustomizePages 0 along with the identity of site collection.

I edit the script as shown below with this additional, however received the same outcome.

![add](https://user-images.githubusercontent.com/43571211/81074030-5bab6880-8ee0-11ea-866f-bcb31b5fa0a6.JPG)

**Comment by anaylor130683** [comment]
This appears similar?

https://gitmemory.com/issue/SharePoint/PnP-Sites-Core/2279/499282920

**Comment by anaylor130683** [comment]
Afternoon 

I have ran this a few times now and it seems to fall down on
Provisioning ClientSitePage : Home.aspx

![debug](https://user-images.githubusercontent.com/43571211/81079748-d6c44d00-8ee7-11ea-9c32-5ddd7378cce9.JPG)

**Comment by EduRemoteLearning** [comment]
Hi Andy,
I've just built a brand new azure VM, implementing the two PowerShell modules required and run the script, creating a new site collection, uploading the images and then applying the template and it has worked fine. I know you've said that you've tried it on a colleagues machine but are you able to try it on a new fresh machine as it appears to be working for us and other partners.
Cheers

**Comment by anaylor130683** [comment]
Hi Alex

You can remove this if you wish.
Although I am confused....

I logged on to a 2016 server and installed the powershell modules and ran the script from the server. It ran through absolutely fine for both of the customers.

I will just continue to do it via the server.

Thanks for your assistance 

Andy

**Comment by EduRemoteLearning** [comment]
No worries - glad its sorted.  If you get the same issue again please open this issue again or if you have another problem please create a new one.
