### ISSUE TITLE
Should we be editing the RemoteLearningTemplate.xml?

### ISSUE THREAD

**Issue by kieranwalsh** [EduRemoteLearning/365edulearning#3]
While troubleshooting a problem I notice that the RemoteLearningTemplate.xml contains these lines:

        <pnp:AdditionalAdministrators>
          <pnp:User Name="i:0#.f|membership|bfcnetworks@newwaveacademycom.onmicrosoft.com" />
          <pnp:User Name="i:0#.f|membership|teacher1@newwaveacademy.com" />
        </pnp:AdditionalAdministrators>
        <pnp:AdditionalOwners>
          <pnp:User Name="i:0#.f|membership|bfcnetworks@newwaveacademycom.onmicrosoft.com" />
          <pnp:User Name="i:0#.f|membership|teacher1@newwaveacademy.com" />
        </pnp:AdditionalOwners>

Should we be changing those to match our sites before running RootSiteCollection.ps1?

**Comment by EduRemoteLearning** [comment]
These should have been removed - they don't need to be removed or change as the PnP provisioning engine will ignore them.  Are you receiving errors from it running and them being in there?

**Comment by kieranwalsh** [comment]
Thanks for clarifying, I'll ignore those lines.
I'm not experiencing errors due to them but I've got errors that are probably due to the same legacy site problems that timguyuk has worked through on another issue. I'm following his suggestions now. Cheers.
