### ISSUE TITLE
Unable to apply template to classic site.

### ISSUE THREAD

**Issue by kieranwalsh** [EduRemoteLearning/365edulearning#4]
I'm working on a site from 2016 that was unused. I believe process is to make a new Modern site and change that to the root site. I've made the new site and apparently in "Active sites" there should be a "replace" option when you click the default root site. That does not show for me.

An alternative is to use this PowerShell command:

`Invoke-SPOSiteSwap -SourceUrl https://tenancy.sharepoint.com/sites/RemoteLearning -TargetUrl https://tenancy.sharepoint.com -ArchiveUrl https://tenancy.sharepoint.com/sites/archivedhome`

but that fails with this error:

> Invoke-SPOSiteSwap : Errors: [0]; Warnings: [8]; Details: The Site is not a communications site or it has the classic publishing feature enabled. more...

If I look in Site Collection Features "SharePoint Server Publishing Infrastructure" is deactivated, so the problem is that it is not a "communications site".

Another alternative is to change the existing classic site to a modern site using this command:

`Enable-SPOCommSite -SiteUrl https://tenancy.sharepoint.com`

Which errors with this:

> Enable-SPOCommSite : The requested operation is part of an experimental feature that is not supported in the current environment.

So I guess that is why "Replace" is not available to me as well? Anyway, that has left me truly stuck. Any idea how to progress?

**Comment by EduRemoteLearning** [comment]
Hi Kieran,
This isn't something we've added to the scope and might be best to log this with Microsoft or with the GitHub repo the command comes from.  
Alex

**Comment by kieranwalsh** [comment]
It looks like the ability to upgrade sites to Modern is being rolled out gradually. Any sites in the same situation will not be able to completed properly.

**Comment by EduRemoteLearning** [comment]
I did look at this when we designed all this but couldn't find that it had been deployed so that's why it wasn't added :-)
